name: ana_page_loop
description: flutter routePage Analytics pluginï¼ŒTry to explore a page to monitor plug-ins
version: 0.1.6
homepage: https://github.com/tec8297729/ana_page_loop

environment:
  sdk: '>=2.2.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
# flutter:
#   plugin:
#     androidPackage: com.example.ana_page_loop
#     pluginClass: AnaPageLoopPlugin
